//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceSplit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SettingsLayout : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsLayout defaultInstance = ((SettingsLayout)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsLayout())));
        
        public static SettingsLayout Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14.25pt, style=Bold")]
        public global::System.Drawing.Font TimerFont {
            get {
                return ((global::System.Drawing.Font)(this["TimerFont"]));
            }
            set {
                this["TimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TimerNotRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerNotRunningColor"]));
            }
            set {
                this["TimerNotRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TimerBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerBackgroundColor"]));
            }
            set {
                this["TimerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color TimerRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerRunningColor"]));
            }
            set {
                this["TimerRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color TimerBehindColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerBehindColor"]));
            }
            set {
                this["TimerBehindColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color TimerPausedColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerPausedColor"]));
            }
            set {
                this["TimerPausedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SplitsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitsBackgroundColor"]));
            }
            set {
                this["SplitsBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CurrentSegmentColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentSegmentColor"]));
            }
            set {
                this["CurrentSegmentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitTimesFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitTimesFont"]));
            }
            set {
                this["SplitTimesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SplitTimesColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitTimesColor"]));
            }
            set {
                this["SplitTimesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitNamesFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitNamesFont"]));
            }
            set {
                this["SplitNamesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SplitNamesColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitNamesColor"]));
            }
            set {
                this["SplitNamesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitDeltasFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitDeltasFont"]));
            }
            set {
                this["SplitDeltasFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color SplitDeltasAheadSavingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasAheadSavingColor"]));
            }
            set {
                this["SplitDeltasAheadSavingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color SplitDeltasAheadLosingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasAheadLosingColor"]));
            }
            set {
                this["SplitDeltasAheadLosingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SplitDeltasBehindSavingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBehindSavingColor"]));
            }
            set {
                this["SplitDeltasBehindSavingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SplitDeltasBehindLosingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBehindLosingColor"]));
            }
            set {
                this["SplitDeltasBehindLosingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color SplitDeltasBestSegmentColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBestSegmentColor"]));
            }
            set {
                this["SplitDeltasBestSegmentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TitleBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["TitleBackgroundColor"]));
            }
            set {
                this["TitleBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font TitleFont {
            get {
                return ((global::System.Drawing.Font)(this["TitleFont"]));
            }
            set {
                this["TitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TitleColor {
            get {
                return ((global::System.Drawing.Color)(this["TitleColor"]));
            }
            set {
                this["TitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font AttemptsFont {
            get {
                return ((global::System.Drawing.Font)(this["AttemptsFont"]));
            }
            set {
                this["AttemptsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color AttemptsColor {
            get {
                return ((global::System.Drawing.Color)(this["AttemptsColor"]));
            }
            set {
                this["AttemptsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GoalBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["GoalBackgroundColor"]));
            }
            set {
                this["GoalBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GoalColor {
            get {
                return ((global::System.Drawing.Color)(this["GoalColor"]));
            }
            set {
                this["GoalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font GoalFont {
            get {
                return ((global::System.Drawing.Font)(this["GoalFont"]));
            }
            set {
                this["GoalFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PreviousSegmentBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentBackgroundColor"]));
            }
            set {
                this["PreviousSegmentBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PreviousSegmentTextColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentTextColor"]));
            }
            set {
                this["PreviousSegmentTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PreviousSegmentTextFont {
            get {
                return ((global::System.Drawing.Font)(this["PreviousSegmentTextFont"]));
            }
            set {
                this["PreviousSegmentTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color PreviousSegmentDeltaSavedColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentDeltaSavedColor"]));
            }
            set {
                this["PreviousSegmentDeltaSavedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color PreviousSegmentDeltaLostColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentDeltaLostColor"]));
            }
            set {
                this["PreviousSegmentDeltaLostColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color PreviousSegmentDeltaBestSegmentColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentDeltaBestSegmentColor"]));
            }
            set {
                this["PreviousSegmentDeltaBestSegmentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PreviousSegmentDeltaFont {
            get {
                return ((global::System.Drawing.Font)(this["PreviousSegmentDeltaFont"]));
            }
            set {
                this["PreviousSegmentDeltaFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PreviousSegmentDeltaNoDeltaColor {
            get {
                return ((global::System.Drawing.Color)(this["PreviousSegmentDeltaNoDeltaColor"]));
            }
            set {
                this["PreviousSegmentDeltaNoDeltaColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PossibleTimeSaveBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PossibleTimeSaveBackgroundColor"]));
            }
            set {
                this["PossibleTimeSaveBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PossibleTimeSaveTextColor {
            get {
                return ((global::System.Drawing.Color)(this["PossibleTimeSaveTextColor"]));
            }
            set {
                this["PossibleTimeSaveTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PossibleTimeSaveTextFont {
            get {
                return ((global::System.Drawing.Font)(this["PossibleTimeSaveTextFont"]));
            }
            set {
                this["PossibleTimeSaveTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PossibleTimeSaveColor {
            get {
                return ((global::System.Drawing.Color)(this["PossibleTimeSaveColor"]));
            }
            set {
                this["PossibleTimeSaveColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PossibleTimeSaveFont {
            get {
                return ((global::System.Drawing.Font)(this["PossibleTimeSaveFont"]));
            }
            set {
                this["PossibleTimeSaveFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PredictedTimeBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["PredictedTimeBackgroundColor"]));
            }
            set {
                this["PredictedTimeBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PredictedTimeTextColor {
            get {
                return ((global::System.Drawing.Color)(this["PredictedTimeTextColor"]));
            }
            set {
                this["PredictedTimeTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PredictedTimeTextFont {
            get {
                return ((global::System.Drawing.Font)(this["PredictedTimeTextFont"]));
            }
            set {
                this["PredictedTimeTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PredictedTimeColor {
            get {
                return ((global::System.Drawing.Color)(this["PredictedTimeColor"]));
            }
            set {
                this["PredictedTimeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font PredictedTimeFont {
            get {
                return ((global::System.Drawing.Font)(this["PredictedTimeFont"]));
            }
            set {
                this["PredictedTimeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SumOfBestBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SumOfBestBackgroundColor"]));
            }
            set {
                this["SumOfBestBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SumOfBestTextColor {
            get {
                return ((global::System.Drawing.Color)(this["SumOfBestTextColor"]));
            }
            set {
                this["SumOfBestTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SumOfBestTextFont {
            get {
                return ((global::System.Drawing.Font)(this["SumOfBestTextFont"]));
            }
            set {
                this["SumOfBestTextFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SumOfBestColor {
            get {
                return ((global::System.Drawing.Color)(this["SumOfBestColor"]));
            }
            set {
                this["SumOfBestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SumOfBestFont {
            get {
                return ((global::System.Drawing.Font)(this["SumOfBestFont"]));
            }
            set {
                this["SumOfBestFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SegmentTimerBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerBackgroundColor"]));
            }
            set {
                this["SegmentTimerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SegmentTimerPBColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerPBColor"]));
            }
            set {
                this["SegmentTimerPBColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SegmentTimerPBFont {
            get {
                return ((global::System.Drawing.Font)(this["SegmentTimerPBFont"]));
            }
            set {
                this["SegmentTimerPBFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SegmentTimerBestColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerBestColor"]));
            }
            set {
                this["SegmentTimerBestColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SegmentTimerBestFont {
            get {
                return ((global::System.Drawing.Font)(this["SegmentTimerBestFont"]));
            }
            set {
                this["SegmentTimerBestFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14.25pt, style=Bold")]
        public global::System.Drawing.Font SegmentTimerFont {
            get {
                return ((global::System.Drawing.Font)(this["SegmentTimerFont"]));
            }
            set {
                this["SegmentTimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SegmentTimerNotRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerNotRunningColor"]));
            }
            set {
                this["SegmentTimerNotRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color SegmentTimerRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerRunningColor"]));
            }
            set {
                this["SegmentTimerRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SegmentTimerLosingTimeColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerLosingTimeColor"]));
            }
            set {
                this["SegmentTimerLosingTimeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color SegmentTimerPausedColor {
            get {
                return ((global::System.Drawing.Color)(this["SegmentTimerPausedColor"]));
            }
            set {
                this["SegmentTimerPausedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LayoutSettingsFile {
            get {
                return ((string)(this["LayoutSettingsFile"]));
            }
            set {
                this["LayoutSettingsFile"] = value;
            }
        }
    }
}
