//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34209
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceSplit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 14.25pt, style=Bold")]
        public global::System.Drawing.Font TimerFont {
            get {
                return ((global::System.Drawing.Font)(this["TimerFont"]));
            }
            set {
                this["TimerFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TimerNotRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerNotRunningColor"]));
            }
            set {
                this["TimerNotRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TimerBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerBackgroundColor"]));
            }
            set {
                this["TimerBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color TimerRunningColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerRunningColor"]));
            }
            set {
                this["TimerRunningColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color TimerBehindColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerBehindColor"]));
            }
            set {
                this["TimerBehindColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color TimerPausedColor {
            get {
                return ((global::System.Drawing.Color)(this["TimerPausedColor"]));
            }
            set {
                this["TimerPausedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color SplitsBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitsBackgroundColor"]));
            }
            set {
                this["SplitsBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color CurrentSegmentColor {
            get {
                return ((global::System.Drawing.Color)(this["CurrentSegmentColor"]));
            }
            set {
                this["CurrentSegmentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitTimesFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitTimesFont"]));
            }
            set {
                this["SplitTimesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SplitTimesColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitTimesColor"]));
            }
            set {
                this["SplitTimesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitNamesFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitNamesFont"]));
            }
            set {
                this["SplitNamesFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color SplitNamesColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitNamesColor"]));
            }
            set {
                this["SplitNamesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font SplitDeltasFont {
            get {
                return ((global::System.Drawing.Font)(this["SplitDeltasFont"]));
            }
            set {
                this["SplitDeltasFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGreen")]
        public global::System.Drawing.Color SplitDeltasAheadSavingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasAheadSavingColor"]));
            }
            set {
                this["SplitDeltasAheadSavingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGreen")]
        public global::System.Drawing.Color SplitDeltasAheadLosingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasAheadLosingColor"]));
            }
            set {
                this["SplitDeltasAheadLosingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SplitDeltasBehindSavingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBehindSavingColor"]));
            }
            set {
                this["SplitDeltasBehindSavingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkRed")]
        public global::System.Drawing.Color SplitDeltasBehindLosingColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBehindLosingColor"]));
            }
            set {
                this["SplitDeltasBehindLosingColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color SplitDeltasBestSegmentColor {
            get {
                return ((global::System.Drawing.Color)(this["SplitDeltasBestSegmentColor"]));
            }
            set {
                this["SplitDeltasBestSegmentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TitleBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["TitleBackgroundColor"]));
            }
            set {
                this["TitleBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font TitleFont {
            get {
                return ((global::System.Drawing.Font)(this["TitleFont"]));
            }
            set {
                this["TitleFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TitleColor {
            get {
                return ((global::System.Drawing.Color)(this["TitleColor"]));
            }
            set {
                this["TitleColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font AttemptsFont {
            get {
                return ((global::System.Drawing.Font)(this["AttemptsFont"]));
            }
            set {
                this["AttemptsFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color AttemptsColor {
            get {
                return ((global::System.Drawing.Color)(this["AttemptsColor"]));
            }
            set {
                this["AttemptsColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GoalBackgroundColor {
            get {
                return ((global::System.Drawing.Color)(this["GoalBackgroundColor"]));
            }
            set {
                this["GoalBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GoalColor {
            get {
                return ((global::System.Drawing.Color)(this["GoalColor"]));
            }
            set {
                this["GoalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt, style=Bold")]
        public global::System.Drawing.Font GoalFont {
            get {
                return ((global::System.Drawing.Font)(this["GoalFont"]));
            }
            set {
                this["GoalFont"] = value;
            }
        }
    }
}
